#!/usr/bin/env python3
"""Regression checks for macOS signoff evidence recording."""

from __future__ import annotations

import importlib.util
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def load_signoff_fixture():
    fixture_path = ROOT / "tools" / "tests" / "macos_signoff_archive.py"
    spec = importlib.util.spec_from_file_location("macos_signoff_archive_fixture", fixture_path)
    if spec is None or spec.loader is None:
        raise AssertionError(f"Unable to import signoff fixture: {fixture_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def require(haystack: str, needle: str, context: str) -> None:
    if needle not in haystack:
        raise AssertionError(f"Missing {needle!r} in {context}")


def reject(haystack: str, needle: str, context: str) -> None:
    if needle in haystack:
        raise AssertionError(f"Unexpected {needle!r} in {context}")


def main() -> int:
    fixture = load_signoff_fixture()
    with tempfile.TemporaryDirectory(prefix="openq4-macos-evidence-") as temp_root:
        temp = Path(temp_root)
        archive = temp / "openq4-macos-results-testrun.tar.gz"
        index = temp / "macos-signoff-evidence.md"
        fixture.write_archive(archive, bridges=("opengl", "metal"), completed=True)
        shutil.copy2(ROOT / "docs" / "dev" / "macos-signoff-evidence.md", index)

        command = [
            sys.executable,
            str(ROOT / "tools" / "macos" / "record_signoff_evidence.py"),
            str(archive),
            "--version",
            "vtest",
            "--package-artifact",
            "openq4-vtest-macos-arm64-opengl.dmg",
            "--package-artifact",
            "openq4-vtest-macos-arm64-metal.dmg",
            "--signing-status",
            "signed and notarized test fixture",
            "--openq4-commit",
            "openq4-test-commit",
            "--gamelibs-commit",
            "openq4-game-test-commit",
            "--release-note-limitation",
            "Apple Silicon/arm64 test limitation",
            "--index",
            str(index),
            "--update-index",
        ]
        result = subprocess.run(
            command,
            cwd=str(ROOT),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True,
        )
        output = result.stdout
        updated_index = index.read_text(encoding="utf-8")

        for token in (
            "### vtest",
            "testrun",
            "Archive SHA-256",
            "passed with --require-completed-checklist",
            "openq4-test-commit",
            "openq4-game-test-commit",
            "Mac mini",
            "Apple M2",
            "Architecture policy",
            "arm64-only experimental release matrix",
            "OS matrix role",
            "latest-public-macos",
            "Latest public macOS evidence",
            "covered by this evidence role: latest-public-macos",
            "Xcode 16.4",
            "macOS SDK version",
            "renderer-mp-smoke",
            "MP loaded `game-mp`, started `mp/q4dm1`",
            "Package layout contract",
            "Mounted DMG launch coverage",
            "fs_basepath, fs_cdpath, and fs_savepath",
            "Gatekeeper assessment",
            "Updated macOS signoff evidence index",
        ):
            require(output, token, "recorded evidence output")

        for token in (
            "Generated by `tools/macos/record_signoff_evidence.py`",
            "- [x] Completed macOS signoff evidence is recorded for run `testrun`.",
            "openq4-vtest-macos-arm64-opengl.dmg, openq4-vtest-macos-arm64-metal.dmg",
            "Apple Silicon/arm64 test limitation",
            "Architecture policy, CPU architecture, and OS matrix role were recorded",
            "Xcode and macOS SDK versions were recorded",
            "macOS floor/latest public signoff coverage was recorded",
            "Copied-package launch was checked",
            "First-class macOS release artifacts are signed/notarized DMGs",
            "### vtest",
        ):
            require(updated_index, token, "updated evidence index")

        reject(
            updated_index,
            "No accepted completed-checklist macOS signoff archive has been recorded yet.",
            "updated evidence index",
        )

    print("macos_evidence_recording: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
