// Generated by tools/build/vulkan_material_sources.py. Do not edit.
// Hashes identify reviewed sources; source text is not embedded.
#ifndef OPENQ4_VK_MATERIAL_SOURCE_SIGNATURES_H
#define OPENQ4_VK_MATERIAL_SOURCE_SIGNATURES_H
struct vkNativeMaterialSourceSignature_t {
    const char *program;
    vkGLSLProgramFamily_t family;
    const char *vertexSHA256;
    const char *fragmentSHA256;
};
static const vkNativeMaterialSourceSignature_t vkNativeMaterialSources[] = {
    {"glsl/displacement.glsl", VK_GLSL_PROGRAM_FAMILY_DISPLACEMENT, "a5a8214e6fc0d115a25dc60f79a291f8e2708a6fdf0586cd37c7c1b51bcefa0f", "adb14ade8b91739e85238596bbc7ab732a1935db226d8ad06221b510f18fdaf0"},
    {"glsl/displacementtwostage.glsl", VK_GLSL_PROGRAM_FAMILY_DISPLACEMENT_TWO_STAGE, "", ""},
    {"glsl/ghostpulling.glsl", VK_GLSL_PROGRAM_FAMILY_GHOST_PULLING, "", ""},
    {"glsl/displacement2.glsl", VK_GLSL_PROGRAM_FAMILY_DISPLACEMENT2, "", ""},
    {"glsl/multiplyblend.glsl", VK_GLSL_PROGRAM_FAMILY_MULTIPLY_BLEND, "38c85930dae950ab5610b00198d851b952d80100406b38c9bc0f344ae03753cd", "0a706a9a25e8b5558dd3d50d98db39348907d34d5e64f10fa5380783f25938a1"},
    {"glsl/displacementcube.glsl", VK_GLSL_PROGRAM_FAMILY_DISPLACEMENT_CUBE, "583f851ea90020613717a219319798c6a62e5be1f0c4c86e4e4aa9dfeda6683f", "f6b0624985a7fc6169c21f83cecd0252c390c38e948e92fa130d87e9329b8160"},
    {"glsl/sniperstretch2.glsl", VK_GLSL_PROGRAM_FAMILY_SNIPER_STRETCH2, "fe6410abb7f9ef224b6cc7c2dc51e5ab3be679b50c0c8f38c5de0bf27fef9f9c", "bb04f74d50eed8f64d18f4382ec122bf360a31a323e95b194417db4c237e2fd1"},
    {"glsl/sniperstretch2.glsl", VK_GLSL_PROGRAM_FAMILY_SNIPER_STRETCH2, "1f23bd1fadaf1aa2c6f5f6dea1896480e8a74d96415622c4ae109070e072b27b", "354db7c6eb41aad13a4d26ba49ebc178704c6c76519061e943d6a0f5aaf5312d"},
    {"glsl/depthtexture.glsl", VK_GLSL_PROGRAM_FAMILY_DEPTH_TEXTURE, "", ""},
    {"glsl/blur.glsl", VK_GLSL_PROGRAM_FAMILY_BLUR, "", ""},
    {"glsl/medlabs.glsl", VK_GLSL_PROGRAM_FAMILY_MEDLABS, "", ""},
    {"glsl/depthtexture2.glsl", VK_GLSL_PROGRAM_FAMILY_DEPTH_TEXTURE2, "", ""},
    {"glsl/al.glsl", VK_GLSL_PROGRAM_FAMILY_AL, "", ""},
    {"glsl/parallaxbump.glsl", VK_GLSL_PROGRAM_FAMILY_PARALLAX_BUMP, "", ""},
    {"glsl/customlit.glsl", VK_GLSL_PROGRAM_FAMILY_CUSTOM_LIT, "", ""},
    {"glsl/water.glsl", VK_GLSL_PROGRAM_FAMILY_WATER, "", ""},
    {"blur.fs", VK_GLSL_PROGRAM_FAMILY_DEPTH_AWARE_BLUR, "77a308f377fc95c3e0a206c91706cc489d73a32e560aad1a9c40f5c2a11421f1", "189971e7aa42aef06f2e464abf254de8c62f15b969c19284c59faccd15344835"},
    {"smaa_edge.fs", VK_GLSL_PROGRAM_FAMILY_SMAA_EDGE, "cbdbbbe08cfe40b4cac0ebdcbd97db2cae33ffdb9bc5245400eae80fa54ab3e1", "c89b2777b0aba93f00be233dc1844710bad75d2e87702d956112e58e63b428af"},
    {"smaa_weights.fs", VK_GLSL_PROGRAM_FAMILY_SMAA_WEIGHTS, "cbdbbbe08cfe40b4cac0ebdcbd97db2cae33ffdb9bc5245400eae80fa54ab3e1", "d0df2a9847a623c872a23c852d78fb39fa88ca7f1515d7ebbe3888503d4d4180"},
    {"smaa_blend.fs", VK_GLSL_PROGRAM_FAMILY_SMAA_BLEND, "cbdbbbe08cfe40b4cac0ebdcbd97db2cae33ffdb9bc5245400eae80fa54ab3e1", "7a164d7be8963869380dceb06d23c852c9a00689762a5c22fe4b13dd52a1bc41"},
};
#endif
